// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FunctionalTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Adding Planes To Cart")]
    [NUnit.Framework.CategoryAttribute("specflow")]
    public partial class AddingPlanesToCartFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddingToPlanesToCart.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Adding Planes To Cart", "\tAs a scale model enthusiast\r\n\tI want to add paper or model planes to my cart\r\n\tS" +
                    "o that I can place an order", ProgrammingLanguage.CSharp, new string[] {
                        "specflow"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding the model \"Fourth Coffee Flyer\" airplane to the cart")]
        [NUnit.Framework.CategoryAttribute("Failing")]
        public virtual void AddingTheModelFourthCoffeeFlyerAirplaneToTheCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding the model \"Fourth Coffee Flyer\" airplane to the cart", new string[] {
                        "Failing"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("I have selected the \"Model Airplanes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.And("I have selected the 1st plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When("I add the plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then("I should be redirected to the cart page\'s url starting with \"http://tailspintoys." +
                    "azurewebsites.net/cart/show\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.And("there should be 1 plane(s) in the cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("the page title\'s should be \"Fourth Coffee Flyer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("the 1st plane\'s description in the cart should be \"Fourth Coffee Flyer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding a third paper \"Wingtip Toys Stunt Plane\" airplane to the cart")]
        [NUnit.Framework.CategoryAttribute("Passing")]
        public virtual void AddingAThirdPaperWingtipToysStuntPlaneAirplaneToTheCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding a third paper \"Wingtip Toys Stunt Plane\" airplane to the cart", new string[] {
                        "Passing"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "Description"});
            table1.AddRow(new string[] {
                        "Model Airplanes",
                        "Trey Research Rocket"});
            table1.AddRow(new string[] {
                        "Model Airplanes",
                        "Northwind Trader"});
#line 23
 testRunner.Given("the cart has the following planes", ((string)(null)), table1, "Given ");
#line 27
 testRunner.And("I have selected the \"Paper Airplanes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("I have selected the 2nd plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("I add the plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("I should be redirected to the cart page\'s url starting with \"http://tailspintoys." +
                    "azurewebsites.net/cart/show\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.And("there should be 3 plane(s) in the cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("the 3rd plane\'s description in the cart should be \"Wingtip Toys Stunt Plane\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("the 3rd plane\'s quantity in the cart should be 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("the 3rd plane\'s total price in the cart should be $50.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Updating the Northwind Trader airplane\'s quantity to 2")]
        [NUnit.Framework.CategoryAttribute("Passing")]
        public virtual void UpdatingTheNorthwindTraderAirplanesQuantityTo2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating the Northwind Trader airplane\'s quantity to 2", new string[] {
                        "Passing"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "Description"});
            table2.AddRow(new string[] {
                        "Paper Airplanes",
                        "Wingtip Toys Stunt Plane"});
            table2.AddRow(new string[] {
                        "Model Airplanes",
                        "Northwind Trader"});
#line 40
 testRunner.Given("the cart has the following planes", ((string)(null)), table2, "Given ");
#line 44
 testRunner.And("I have navigated to the cart page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.When("I update the quantity 3 for 2nd plane\'s in the cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
 testRunner.Then("there should be 2 plane(s) in the cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
 testRunner.And("the 1st plane\'s quantity in the cart should be 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("the 1st plane\'s total price in the cart should be $50.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("the 2nd plane\'s quantity in the cart should be 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("the 2nd plane\'s total price in the cart should be $150.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
