// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FunctionalTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("third party multiple browser testing")]
    [NUnit.Framework.CategoryAttribute("specflow")]
    public partial class ThirdPartyMultipleBrowserTestingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ThirdPartySeleniumGrid.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "third party multiple browser testing", "\tAs a developer\r\n\tI would like to run my specflow scenario on third party seleniu" +
                    "m grid runner\r\n\tSo that I do not need to update my VM and I can test on the late" +
                    "st browsers", ProgrammingLanguage.CSharp, new string[] {
                        "specflow"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding the model \"Fourth Coffee Flyer\" airplane to the cart")]
        [NUnit.Framework.CategoryAttribute("BrowserStack")]
        [NUnit.Framework.TestCaseAttribute("Chrome", "50.0", "Windows", "8", null)]
        [NUnit.Framework.TestCaseAttribute("Safari", "10.0", "OS X", "Sierra", null)]
        [NUnit.Framework.TestCaseAttribute("Edge", "15.0", "Windows", "10", null)]
        public virtual void AddingTheModelFourthCoffeeFlyerAirplaneToTheCart(string browser, string version, string osName, string osVersion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "BrowserStack"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding the model \"Fourth Coffee Flyer\" airplane to the cart", @__tags);
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given(string.Format("the selected browser is {0} {1} on {2} {3}", browser, version, osName, osVersion), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.And("I have selected the \"Model Airplanes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I have selected the 1st plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When("I add the plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then("I should be redirected to the cart page\'s url starting with \"http://tailspintoys." +
                    "azurewebsites.net/cart/show\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.And("there should be 1 plane(s) in the cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("the 1st plane\'s description in the cart should be \"Fourth Coffee Flyer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding the model \"Trey Research Rocket\" airplane to the cart")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("SauceLabs")]
        [NUnit.Framework.TestCaseAttribute("chrome", "50.0", "Windows", "10", null)]
        [NUnit.Framework.TestCaseAttribute("Safari", "9.0", "OS X", "El Capitan", null)]
        [NUnit.Framework.TestCaseAttribute("IE", "", "", "", null)]
        public virtual void AddingTheModelTreyResearchRocketAirplaneToTheCart(string browser, string version, string osName, string osVersion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ignore",
                    "SauceLabs"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding the model \"Trey Research Rocket\" airplane to the cart", @__tags);
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given(string.Format("the browser is is {0} {1} on {2} {3}", browser, version, osName, osVersion), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.And("I have selected the \"Model Airplanes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("I have selected the 2nd plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.When("I add the plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("I should be redirected to the cart page\'s url starting with \"http://tailspintoys." +
                    "azurewebsites.net/cart/show\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.And("there should be 1 plane(s) in the cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("the 1st plane\'s description in the cart should be \"Fourth Coffee Flyer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding the model \"Wingtip Toys Stunt Plane\" airplane to the cart")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("browser:chrome,50.0,Windows,10")]
        [NUnit.Framework.CategoryAttribute("browser:firefox")]
        [NUnit.Framework.CategoryAttribute("browser:IE,800x600")]
        public virtual void AddingTheModelWingtipToysStuntPlaneAirplaneToTheCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding the model \"Wingtip Toys Stunt Plane\" airplane to the cart", new string[] {
                        "ignore",
                        "browser:chrome,50.0,Windows,10",
                        "browser:firefox",
                        "browser:IE,800x600"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 54
 testRunner.Given("I have selected the 2nd plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
 testRunner.And("I have selected the \"Paper Airplanes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.When("I add the plane", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.Then("I should be redirected to the cart page\'s url starting with \"http://tailspintoys." +
                    "azurewebsites.net/cart/show\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 58
 testRunner.And("there should be 1 plane(s) in the cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("the 1st plane\'s description in the cart should be \"Trey Research Rocket\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
